### ISSUE TITLE
Does 2 factor authentication work?

### ISSUE THREAD

**Issue by devalirzayev** [threadsjs/threads.js#85]
I have enabled 2fa on Threads account and tried to post via threads.js. It crashes.

Crash message:

```
 const sanitized = JSON.parse(JSON.parse(tree['㐟']['#'].match(/\"\{.*\}\"/)[0]));
                                                                                                                        ^

TypeError: Cannot read properties of null (reading '0')
    at parseBloksResponse (/Users/devalirzayev/Projects/threads.js/src/util/Bloks.js:33:76)
    at Client.login (/Users/devalirzayev/Projects/threads.js/src/index.js:138:17)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async /Users/devalirzayev/Projects/threads.js/src/demo.js:6:5

Node.js v21.7.2
```

**Comment by elijah-wright** [comment]
the code that was written when Threads came out is probably outdated, so it doesn't surprise me that it doesn't work

I plan on writing the official API soon, so if you're fine with waiting until June. testing the unofficial Threads API is difficult because Instagram has anti-bot measures that will lock your account, sometimes requiring you to upload a picture of your face

**Comment by devalirzayev** [comment]
@elijah-wright, thanks for reply.

We have reverse engineered web version of threads as it is easier than app and works. But as you said it is not stable. Anti-bot system flags accounts too often.
